/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Richo Novian Saputra
 */
public class DataMahasiswa extends javax.swing.JFrame {
    
    Connection con = null;
    Statement statBrg = null;
    ResultSet rs = null;

    /**
     * Creates new form Dashboard
     */
    public DataMahasiswa() {
        initComponents();
        koneksi();
        display();
        MhsTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMhsMouseClicked(evt);
            }
        });
    }
    
    private void koneksi() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://127.0.0.1:3307/dbakademik"; 
            String user="root"; 
            String pass=""; 
            con = DriverManager.getConnection(url,user,pass);
            statBrg = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = statBrg.executeQuery("SELECT * FROM mahasiswa");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void display() {
        String sql="SELECT * FROM mahasiswa";
        try (PreparedStatement pst = con.prepareStatement(sql);
             ResultSet rs = pst.executeQuery()) {
            MhsTabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        formDsnLbl = new javax.swing.JLabel();
        formMhsLbl = new javax.swing.JLabel();
        formMKLbl = new javax.swing.JLabel();
        formPerkuliahanLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        iconLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MhsTabel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        kelMhsLbl = new javax.swing.JLabel();
        nimLbl = new javax.swing.JLabel();
        nimField = new javax.swing.JTextField();
        namaMhsLbl = new javax.swing.JLabel();
        namaMhsField = new javax.swing.JTextField();
        insertBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        tglLahirLbl = new javax.swing.JLabel();
        tglLahirField = new javax.swing.JTextField();
        alamatLbl = new javax.swing.JLabel();
        alamatField = new javax.swing.JTextField();
        JKLbl = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        JKRadioBtn1 = new javax.swing.JRadioButton();
        JKRadioBtn2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 65));

        titleLbl.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("SISTEM INFORMASI MANAJEMEN AKADEMIK");

        formDsnLbl.setForeground(new java.awt.Color(255, 255, 255));
        formDsnLbl.setText("Data Dosen");
        formDsnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formDsnLblMouseClicked(evt);
            }
        });

        formMhsLbl.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        formMhsLbl.setForeground(new java.awt.Color(255, 255, 255));
        formMhsLbl.setText("Data Mahasiswa");

        formMKLbl.setForeground(new java.awt.Color(255, 255, 255));
        formMKLbl.setText("Data Mata Kuliah");
        formMKLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMKLblMouseClicked(evt);
            }
        });

        formPerkuliahanLbl.setForeground(new java.awt.Color(255, 255, 255));
        formPerkuliahanLbl.setText("Data Perkuliahan");
        formPerkuliahanLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formPerkuliahanLblMouseClicked(evt);
            }
        });

        iconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/database-storage (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(iconLbl)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(formDsnLbl)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(formMhsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addComponent(formMKLbl)
                        .addGap(50, 50, 50)
                        .addComponent(formPerkuliahanLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(titleLbl)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formDsnLbl)
                    .addComponent(formMhsLbl)
                    .addComponent(formMKLbl)
                    .addComponent(formPerkuliahanLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        MhsTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama Mahasiswa", "Tanggal Lahir", "Alamat", "Jenis Kelamin"
            }
        ));
        jScrollPane1.setViewportView(MhsTabel);

        jPanel3.setBackground(new java.awt.Color(0, 105, 107));

        kelMhsLbl.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        kelMhsLbl.setForeground(new java.awt.Color(255, 255, 255));
        kelMhsLbl.setText("Kelola Data Mahasiswa");

        nimLbl.setForeground(new java.awt.Color(255, 255, 255));
        nimLbl.setText("NIM :");

        nimField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nimField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimFieldActionPerformed(evt);
            }
        });

        namaMhsLbl.setForeground(new java.awt.Color(255, 255, 255));
        namaMhsLbl.setText("Nama Mahasiswa :");

        namaMhsField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        insertBtn.setBackground(new java.awt.Color(0, 174, 27));
        insertBtn.setText("Insert");
        insertBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(255, 236, 8));
        editBtn.setText("Edit");
        editBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        tglLahirLbl.setForeground(new java.awt.Color(255, 255, 255));
        tglLahirLbl.setText("Tanggal Lahir :");

        tglLahirField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        alamatLbl.setForeground(new java.awt.Color(255, 255, 255));
        alamatLbl.setText("Alamat :");

        alamatField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        JKLbl.setForeground(new java.awt.Color(255, 255, 255));
        JKLbl.setText("Jenis Kelamin :");

        logoutBtn.setBackground(new java.awt.Color(255, 0, 0));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        JKRadioBtn1.setForeground(new java.awt.Color(255, 255, 255));
        JKRadioBtn1.setText("Laki-laki");
        JKRadioBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JKRadioBtn1ActionPerformed(evt);
            }
        });

        JKRadioBtn2.setForeground(new java.awt.Color(255, 255, 255));
        JKRadioBtn2.setText("Perempuan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(kelMhsLbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(JKRadioBtn1)
                                .addGap(18, 18, 18)
                                .addComponent(JKRadioBtn2))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(alamatLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nimLbl)
                                .addComponent(namaMhsLbl)
                                .addComponent(namaMhsField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                .addComponent(nimField)
                                .addComponent(tglLahirLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tglLahirField)
                                .addComponent(alamatField)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(JKLbl)))))
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(kelMhsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nimLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nimField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaMhsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaMhsField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglLahirLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglLahirField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JKLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JKRadioBtn1)
                    .addComponent(JKRadioBtn2))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void nimFieldActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        String nim = nimField.getText();
        String nama = namaMhsField.getText();
        String tglLahir = tglLahirField.getText();
        String alamat = alamatField.getText();
        String jenisKelamin = JKRadioBtn1.isSelected() ? "Laki-laki" : "Perempuan";
        
        if (nim.isEmpty() || nama.isEmpty() || tglLahir.isEmpty() || alamat.isEmpty() || (!JKRadioBtn1.isSelected() && !JKRadioBtn2.isSelected())) {
            JOptionPane.showMessageDialog(null, "Pilih data mahasiswa yang ingin diubah.");
            return;
        }

        String sql = "UPDATE mahasiswa SET Nama_Mhs = ?, Tgl_Lahir = ?, Alamat = ?, Jenis_Kelamin = ? WHERE Nim = ?";
        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, nama);
            pst.setString(2, tglLahir);
            pst.setString(3, alamat);
            pst.setString(4, jenisKelamin);
            pst.setString(5, nim);
            int updated = pst.executeUpdate();
            if (updated > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui");
                display(); // Refresh table view
            } else {
                JOptionPane.showMessageDialog(null, "Data gagal diperbarui");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        clearData();
    }                                       

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String nim = nimField.getText(); // Get the NIM from the text field

        if (nim.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih data mahasiswa yang ingin dihapus.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Penghapusan", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM mahasiswa WHERE Nim = ?";
            try (PreparedStatement pst = con.prepareStatement(sql)) {
                pst.setString(1, nim);
                int deleted = pst.executeUpdate();
                if (deleted > 0) {
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                    display(); // Refresh table view
                } else {
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

        clearData();
    }                                         

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String nim = nimField.getText();
        String nama = namaMhsField.getText();
        String tglLahir = tglLahirField.getText();
        String alamat = alamatField.getText();
        String jenisKelamin = JKRadioBtn1.isSelected() ? "Laki-laki" : "Perempuan";
        
        if (nim.isEmpty() || nama.isEmpty() || tglLahir.isEmpty() || alamat.isEmpty() || (!JKRadioBtn1.isSelected() && !JKRadioBtn2.isSelected())) {
            JOptionPane.showMessageDialog(null, "NIM, Nama Mahasiswa, Tanggal Lahir, Alamat, dan Jenis Kelamin tidak boleh kosong.");
            return;
        }

        String sql = "INSERT INTO mahasiswa (Nim, Nama_Mhs, Tgl_Lahir, Alamat, Jenis_Kelamin) VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, nim);
            pst.setString(2, nama);
            pst.setString(3, tglLahir);
            pst.setString(4, alamat);
            pst.setString(5, jenisKelamin);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
            display(); // Refresh table view
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        clearData();
    }                                         

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void formDsnLblMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        DataDosen dataDosen = new DataDosen();
        dataDosen.setVisible(true);
        this.dispose();
    }                                       

    private void formMKLblMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        DataMataKuliah dataMataKuliah = new DataMataKuliah();
        dataMataKuliah.setVisible(true);
        this.dispose();
    }                                      

    private void formPerkuliahanLblMouseClicked(java.awt.event.MouseEvent evt) {                                                
        // TODO add your handling code here:
        DataPerkuliahan dataPerkuliahan = new DataPerkuliahan();
        dataPerkuliahan.setVisible(true);
        this.dispose();
    }                                               

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }                                      

    private void tabelMhsMouseClicked(java.awt.event.MouseEvent evt) {                                      
        try {
            int row = MhsTabel.getSelectedRow();
            String tableClick = (MhsTabel.getModel().getValueAt(row, 0).toString());
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT * FROM mahasiswa WHERE Nim ='" + tableClick + "'");
            if (rs.next()) {
                String nim = rs.getString("Nim");
                nimField.setText(nim);
                String nama = rs.getString("Nama_Mhs");
                namaMhsField.setText(nama);
                String tglLahir = rs.getString("Tgl_Lahir");
                tglLahirField.setText(tglLahir);
                String alamat = rs.getString("Alamat");
                alamatField.setText(alamat);
                String jenisKelamin = rs.getString("Jenis_Kelamin");
                if (jenisKelamin.equals("Laki-laki")) {
                    JKRadioBtn1.setSelected(true);
                } else {
                    JKRadioBtn2.setSelected(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void clearData() {
        nimField.setText("");
        namaMhsField.setText("");
        tglLahirField.setText("");
        alamatField.setText("");
        JKRadioBtn1.setSelected(false);
        JKRadioBtn2.setSelected(false);
    }
    
    private void JKRadioBtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel JKLbl;
    private javax.swing.JRadioButton JKRadioBtn1;
    private javax.swing.JRadioButton JKRadioBtn2;
    private javax.swing.JTable MhsTabel;
    private javax.swing.JTextField alamatField;
    private javax.swing.JLabel alamatLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel formDsnLbl;
    private javax.swing.JLabel formMKLbl;
    private javax.swing.JLabel formMhsLbl;
    private javax.swing.JLabel formPerkuliahanLbl;
    private javax.swing.JLabel iconLbl;
    private javax.swing.JButton insertBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel kelMhsLbl;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField namaMhsField;
    private javax.swing.JLabel namaMhsLbl;
    private javax.swing.JTextField nimField;
    private javax.swing.JLabel nimLbl;
    private javax.swing.JTextField tglLahirField;
    private javax.swing.JLabel tglLahirLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration                   
}
