/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Richo Novian Saputra
 */
public class DataPerkuliahan extends javax.swing.JFrame {
    Connection con = null;
    Statement statBrg = null;
    ResultSet rs = null;

    /**
     * Creates new form Dashboard
     */
    public DataPerkuliahan() {
        initComponents();
        koneksi();
        display();
        perkuliahanTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perkuliahanTabelMouseClicked(evt);
            }
        });
    }
    
    private void koneksi() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://127.0.0.1:3307/dbakademik"; 
            String user="root"; 
            String pass=""; 
            con = DriverManager.getConnection(url,user,pass);
            statBrg = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = statBrg.executeQuery("SELECT * FROM perkuliahan");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void display() {
        String sql="SELECT * FROM perkuliahan";
        try (PreparedStatement pst = con.prepareStatement(sql);
             ResultSet rs = pst.executeQuery()) {
            perkuliahanTabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        formDsnLbl = new javax.swing.JLabel();
        formMhsLbl = new javax.swing.JLabel();
        formMKLbl = new javax.swing.JLabel();
        formPerkuliahanLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        iconLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        perkuliahanTabel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        kelPerkuliahanLbl = new javax.swing.JLabel();
        nimLbl = new javax.swing.JLabel();
        nimField = new javax.swing.JTextField();
        kodeMKLbl = new javax.swing.JLabel();
        kodeMKField = new javax.swing.JTextField();
        InsertBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        nipLbl = new javax.swing.JLabel();
        nipField = new javax.swing.JTextField();
        nilaiLbl = new javax.swing.JLabel();
        nilaiField = new javax.swing.JTextField();
        logoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 65));

        titleLbl.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("SISTEM INFORMASI MANAJEMEN AKADEMIK");

        formDsnLbl.setForeground(new java.awt.Color(255, 255, 255));
        formDsnLbl.setText("Data Dosen");
        formDsnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formDsnLblMouseClicked(evt);
            }
        });

        formMhsLbl.setForeground(new java.awt.Color(255, 255, 255));
        formMhsLbl.setText("Data Mahasiswa");
        formMhsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMhsLblMouseClicked(evt);
            }
        });

        formMKLbl.setForeground(new java.awt.Color(255, 255, 255));
        formMKLbl.setText("Data Mata Kuliah");
        formMKLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMKLblMouseClicked(evt);
            }
        });

        formPerkuliahanLbl.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        formPerkuliahanLbl.setForeground(new java.awt.Color(255, 255, 255));
        formPerkuliahanLbl.setText("Data Perkuliahan");

        iconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/database-storage (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(iconLbl)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formDsnLbl)
                        .addGap(45, 45, 45)
                        .addComponent(formMhsLbl)
                        .addGap(49, 49, 49)
                        .addComponent(formMKLbl)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(formPerkuliahanLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(titleLbl)
                        .addContainerGap(78, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formDsnLbl)
                    .addComponent(formMhsLbl)
                    .addComponent(formMKLbl)
                    .addComponent(formPerkuliahanLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        perkuliahanTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIM", "Kode Mata Kuliah", "NIP", "Nilai"
            }
        ));
        jScrollPane1.setViewportView(perkuliahanTabel);

        jPanel3.setBackground(new java.awt.Color(0, 105, 107));

        kelPerkuliahanLbl.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        kelPerkuliahanLbl.setForeground(new java.awt.Color(255, 255, 255));
        kelPerkuliahanLbl.setText("Kelola Data Perkuliahan");

        nimLbl.setForeground(new java.awt.Color(255, 255, 255));
        nimLbl.setText("NIM :");

        nimField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nimField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimFieldActionPerformed(evt);
            }
        });

        kodeMKLbl.setForeground(new java.awt.Color(255, 255, 255));
        kodeMKLbl.setText("Kode Mata Kuliah :");

        kodeMKField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        InsertBtn.setBackground(new java.awt.Color(0, 174, 27));
        InsertBtn.setText("Insert");
        InsertBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        InsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBtnActionPerformed(evt);
            }
        });

        EditBtn.setBackground(new java.awt.Color(255, 236, 8));
        EditBtn.setText("Edit");
        EditBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        DeleteBtn.setText("Delete");
        DeleteBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        nipLbl.setForeground(new java.awt.Color(255, 255, 255));
        nipLbl.setText("NIP :");

        nipField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        nilaiLbl.setForeground(new java.awt.Color(255, 255, 255));
        nilaiLbl.setText("Nilai :");

        nilaiField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        logoutBtn.setBackground(new java.awt.Color(255, 0, 0));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(kelPerkuliahanLbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nilaiLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nipLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(InsertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nimLbl)
                            .addComponent(kodeMKLbl)
                            .addComponent(kodeMKField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(nimField)
                            .addComponent(nipField)
                            .addComponent(nilaiField))))
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(kelPerkuliahanLbl)
                .addGap(28, 28, 28)
                .addComponent(nimLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nimField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kodeMKLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodeMKField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nipLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nipField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nilaiLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nilaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void nimFieldActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        String nim = nimField.getText();
        String kodeMK = kodeMKField.getText();
        String nip = nipField.getText();
        String nilai = nilaiField.getText();
        
        if (nim.isEmpty() || kodeMK.isEmpty() || nip.isEmpty() || nilai.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih data perkuliahan yang ingin diubah.");
            return;
        }

        String sql = "UPDATE perkuliahan SET Nim = ?, Kode_MK = ?, Nip = ?, Nilai = ? WHERE Nim = ? AND Kode_MK = ? AND Nip = ?";
        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, nim);
            pst.setString(2, kodeMK);
            pst.setString(3, nip);
            pst.setString(4, nilai);
            pst.setString(5, nim); // Assuming Nim is part of the primary key or unique identifier
            pst.setString(6, kodeMK); // Assuming Kode_MK is part of the primary key or unique identifier
            pst.setString(7, nip); // Assuming Nip is part of the primary key or unique identifier
            int affectedRows = pst.executeUpdate();
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui");
                display(); // Refresh table view
            } else {
                JOptionPane.showMessageDialog(null, "Tidak ada data yang diperbarui");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

        clearData();
    }                                       

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String nim = nimField.getText();
        String kodeMK = kodeMKField.getText();
        String nip = nipField.getText();
        String nilai = nilaiField.getText();
        
        if (nim.isEmpty() || kodeMK.isEmpty() || nip.isEmpty() || nilai.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih data perkuliahan yang ingin dihapus.");
            return;
        }

        String sql = "DELETE FROM perkuliahan WHERE Nim = ? AND Kode_MK = ? AND Nip = ?";
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data ini?", 
                "Konfirmasi Penghapusan", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try (PreparedStatement pst = con.prepareStatement(sql)) {
                pst.setString(1, nim);
                pst.setString(2, kodeMK);
                pst.setString(3, nip);
                int affectedRows = pst.executeUpdate();
                if (affectedRows > 0) {
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                    display(); // Refresh table view
                } else {
                    JOptionPane.showMessageDialog(null, "Tidak ada data yang dihapus");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
        }

        clearData();
    }                                         

    private void InsertBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String nim = nimField.getText();
        String kodeMK = kodeMKField.getText();
        String nip = nipField.getText();
        String nilai = nilaiField.getText();
        
        if (nim.isEmpty() || kodeMK.isEmpty() || nip.isEmpty() || nilai.isEmpty()) {
            JOptionPane.showMessageDialog(null, "NIM, Kode Mata Kuliah, NIP, dan Nilai tidak boleh kosong.");
            return;
        }

        String sql = "INSERT INTO perkuliahan (Nim, Kode_MK, Nip, Nilai) VALUES (?, ?, ?, ?)";
        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, nim);
            pst.setString(2, kodeMK);
            pst.setString(3, nip);
            pst.setString(4, nilai);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
            display(); // Refresh table view
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

        clearData();
    }                                         

    private void formDsnLblMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        DataDosen dataDosen = new DataDosen();
        dataDosen.setVisible(true);
        this.dispose();
    }                                       

    private void formMhsLblMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        DataMahasiswa dataMahasiswa = new DataMahasiswa();
        dataMahasiswa.setVisible(true);
        this.dispose();
    }                                       

    private void formMKLblMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        DataMataKuliah dataMataKuliah = new DataMataKuliah();
        dataMataKuliah.setVisible(true);
        this.dispose();
    }                                      

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }                                      

    private void perkuliahanTabelMouseClicked(java.awt.event.MouseEvent evt) {                                          
        try {
            int row = perkuliahanTabel.getSelectedRow();
            String tableClick = (perkuliahanTabel.getModel().getValueAt(row, 0).toString()); // Assuming the first column is 'Nim'
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT * FROM perkuliahan WHERE Nim ='" + tableClick + "'");
            if (rs.next()) {
                String nim = rs.getString("Nim");
                nimField.setText(nim);
                String kodeMK = rs.getString("Kode_MK");
                kodeMKField.setText(kodeMK);
                String nip = rs.getString("Nip");
                nipField.setText(nip);
                String nilai = rs.getString("Nilai");
                nilaiField.setText(nilai);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void clearData() {
        nimField.setText("");
        kodeMKField.setText("");
        nipField.setText("");
        nilaiField.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPerkuliahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPerkuliahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPerkuliahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPerkuliahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPerkuliahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton InsertBtn;
    private javax.swing.JLabel formDsnLbl;
    private javax.swing.JLabel formMKLbl;
    private javax.swing.JLabel formMhsLbl;
    private javax.swing.JLabel formPerkuliahanLbl;
    private javax.swing.JLabel iconLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel kelPerkuliahanLbl;
    private javax.swing.JTextField kodeMKField;
    private javax.swing.JLabel kodeMKLbl;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField nilaiField;
    private javax.swing.JLabel nilaiLbl;
    private javax.swing.JTextField nimField;
    private javax.swing.JLabel nimLbl;
    private javax.swing.JTextField nipField;
    private javax.swing.JLabel nipLbl;
    private javax.swing.JTable perkuliahanTabel;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration                   
}
